export const SETTINGS_TEXT_BASE: Record<string, string> = {
  "Add 'saved' tag": "添加“已保存”标签",
  "Add new tag": "添加新标签",
  "Add new word": "添加新单词",
  "Add tag": "添加标签",
  "Add word": "添加单词",
  Alignment: "对齐方式",
  "Allow image caching": "允许缓存图片",
  Apply: "应用",
  "Apply metadata data.json location change":
    "应用 metadata data.json 位置更改",
  "Apply metadata location": "应用 metadata 位置",
  "Apply metadata location changes independently from feed storage mode.":
    "独立于订阅源存储模式应用 metadata 位置更改。",
  "Apply the selected storage mode and/or folder location":
    "应用所选存储模式和/或文件夹位置",
  "Apply the selected storage mode, repair shard files, or import/export a portable data bundle (everything), a feed bundle (feeds, folders, tags, articles, and article state — no app settings), or a settings bundle (app preferences only) for desktop/mobile transfer workflows.":
    "应用所选存储模式、修复分片文件，或导入/导出便携数据包（全部数据）、订阅源数据包（订阅源、文件夹、标签、文章及文章状态，不含应用设置）或设置数据包（仅应用偏好），用于桌面与移动设备之间的数据迁移。",
  "Article date display": "文章日期显示",
  "All feeds badge": "全部订阅源未读数标记",
  "Add default Mastodon tags": "添加默认 Mastodon 标签",
  "Add default podcast tags": "添加默认播客标签",
  "Auto backups": "自动备份",
  "Auto tagging": "自动添加标签",
  "Auto-refresh interval": "自动刷新间隔",
  "Automatically add a 'saved' tag to saved articles":
    "保存文章时自动添加“已保存”标签",
  'Automatically mark article "read" upon opening': "打开文章时自动标记为已读",
  "Automatically create backup copies of your data files when the plugin closes.":
    "插件关闭时自动备份数据文件。",
  "Back up data.json": "备份 data.json",
  "Back up feeds": "备份订阅源",
  "Back up user preferences": "备份用户偏好",
  "Backup & restore (data.json)": "备份与恢复（data.json）",
  "Base URL of the CORS proxy.": "CORS 代理的基础 URL。",
  "Buy me a coffee": "请我喝杯咖啡",
  Cancel: "取消",
  "Card spacing": "卡片间距",
  "Cards per row": "每行卡片数",
  Case: "大小写",
  "Case sensitive": "区分大小写",
  "Catppuccin mocha": "Catppuccin 摩卡",
  Clear: "清除",
  "Clear image cache": "清除图片缓存",
  "Clear image cache?": "清除图片缓存？",
  "Clear progress": "清除播放进度",
  "Clear saved playback progress": "清除已保存的播放进度",
  "Choose a visual theme for the podcast player": "选择播客播放器的外观主题",
  "Choose between list, card, and feed view for articles":
    "选择文章的列表、卡片或订阅流视图",
  "Choose how action buttons are laid out in mobile list view":
    "选择移动端列表视图中操作按钮的布局",
  "Choose how reader paragraphs align": "选择阅读器段落的对齐方式",
  "Choose the reader body font size preset": "选择阅读器正文字号",
  "Choose the reader font family": "选择阅读器字体",
  "Choose the reader line height preset": "选择阅读器行高",
  "Choose the spacing between reader paragraphs": "选择阅读器段落间距",
  "Choose where to open articles/media when clicked":
    "选择点击文章或媒体后的打开位置",
  "Choose where to open saved article files": "选择已保存文章文件的打开位置",
  "Choose where to open the RSS dashboard": "选择 RSS 面板的打开位置",
  "Choose whether article dates are shown as relative ('2 days ago') or absolute ('may 9, 2026').":
    "选择文章日期显示为相对时间（如“2 天前”）还是具体日期（如“2026 年 5 月 9 日”）。",
  "Choose whether dashboard pagination appears above or below the articles":
    "选择面板分页显示在文章上方还是下方",
  "Choose which filters to apply when opening the dashboard.":
    "选择打开面板时自动应用的筛选条件。",
  "Controls pagination page size across all dashboard views.":
    "设置所有面板视图的每页文章数量。",
  "Dashboard view location": "面板打开位置",
  "Copy build details": "复制构建信息",
  "Copy feed bundle to clipboard": "复制订阅源数据包",
  "Copy feeds.opml to clipboard": "复制 feeds.opml",
  "Copy legacy data.json to clipboard": "复制旧版 data.json",
  "Copy settings bundle to clipboard": "复制设置数据包",
  "Copy shard data to clipboard": "复制分片数据",
  "Copy user preferences to clipboard": "复制用户偏好",
  "Data is stored locally.": "数据存储在本地。",
  "Data retention": "数据保留",
  "Default article template": "默认文章模板",
  "Default auto delete duration (new feeds)": "新订阅源的默认自动删除周期",
  "Default days to keep read articles before auto-delete for new feeds (per-feed override available). This will also limit the timeframe window for shown articles.":
    "新订阅源中已读文章自动删除前的保留天数（可单独设置订阅源）。此设置也会限制文章显示的时间范围。",
  "Default folder to save articles": "保存文章的默认文件夹",
  "Default folders": "默认文件夹",
  "Default Mastodon tag": "默认 Mastodon 标签",
  "Default podcast tag": "默认播客标签",
  "Default RSS tag": "默认 RSS 标签",
  "Default smallweb tag": "默认 Smallweb 标签",
  "Default video tag": "默认视频标签",
  "Default YouTube tag": "默认 YouTube 标签",
  "Default max item limit for new feeds (and fallback when a feed has no override).":
    "新订阅源的默认文章数量上限（订阅源未单独设置时也使用此值）。",
  "Default play speed": "默认播放速度",
  "Default tag names": "恢复默认标签名称",
  "Default template": "默认模板",
  "Delay before the initial refresh when Obsidian opens, in seconds.":
    "Obsidian 启动后首次刷新的等待秒数。",
  "Delete tag": "删除标签",
  "Delete this template": "删除此模板",
  "Display content summary in card view": "在卡片视图中显示内容摘要",
  "Display cover-image previews in dashboard card and feed views. Turning this off reduces remote image loading and can improve browsing performance.":
    "在面板卡片和订阅流视图中显示封面预览。关闭后会减少远程图片加载并提升浏览性能。",
  "Do not limit total image-cache storage. The one-megabyte limit for each image still applies.":
    "不限制图片缓存总量。单张图片仍限制为 1 MB。",
  "Enabled | color picker | hex input":
    "启用状态 | 颜色选择器 | 十六进制颜色值",
  "Enable CORS proxy": "启用 CORS 代理",
  "Enable word highlighting": "启用单词高亮",
  "Enter tag name": "输入标签名称",
  "Enter word to highlight": "输入要高亮的单词",
  "Export OPML": "导出 OPML",
  "Export feed bundle": "导出订阅源数据包",
  "Export legacy data.json": "导出旧版 data.json",
  "Export portable data bundle": "导出便携数据包",
  "Export settings bundle": "导出设置数据包",
  "Export shard data": "导出分片数据",
  "Export user preferences": "导出用户偏好",
  "External browser": "外部浏览器",
  "Factory reset": "恢复出厂设置",
  "Failed to delete one or more previous metadata files.":
    "无法删除一个或多个旧 metadata 文件。",
  "Feed bundle": "订阅源数据包",
  "Feed icons": "订阅源图标",
  "Fetch and save the full article content from the web (instead of just the RSS summary)":
    "从网页获取并保存完整文章内容，而不只是 RSS 摘要",
  "Fetch timeout": "获取超时时间",
  Font: "字体",
  "Font size": "字号",
  "Folder names restored to defaults.": "文件夹名称已恢复默认值。",
  "Global feeds": "全局订阅源",
  "Hide all icons in the sidebar header": "隐藏侧边栏标题栏中的所有图标",
  "Hide default RSS icon": "隐藏默认 RSS 图标",
  "Hide empty feeds/no unread articles": "隐藏空订阅源或没有未读文章的订阅源",
  "Hide feeds in the sidebar if they have zero articles or zero unread articles":
    "订阅源没有文章或没有未读文章时，在侧边栏中隐藏它",
  "Hide the default RSS icon for regular feeds in the sidebar":
    "在侧边栏中隐藏普通订阅源的默认 RSS 图标",
  "Folders badge": "文件夹未读数标记",
  "Highlight color": "高亮颜色",
  "Highlight in content": "高亮正文",
  "Highlight in summaries": "高亮摘要",
  "Highlight in titles": "高亮标题",
  "Highlight locations": "高亮位置",
  "Highlight specified words in article titles, summaries, and content":
    "在文章标题、摘要和正文中高亮指定单词",
  "Highlight words": "高亮单词",
  "How often to auto-refresh feeds (in minutes)":
    "自动刷新订阅源的间隔（分钟）",
  "Icon visibility": "图标显示",
  "Image cache limit": "图片缓存上限",
  "Import OPML/XML": "导入 OPML/XML",
  "Import failed: invalid or corrupted data file.":
    "导入失败：数据文件无效或已损坏。",
  "Import feed bundle": "导入订阅源数据包",
  "Import legacy data.json": "导入旧版 data.json",
  "Import portable data bundle": "导入便携数据包",
  "Import settings bundle": "导入设置数据包",
  "Import shard data": "导入分片数据",
  "Import starred articles": "导入已加星标的文章",
  "Import user preferences": "导入用户偏好",
  "Import or export an OPML subscription list containing your configured feed addresses.":
    "导入或导出包含已配置订阅源地址的 OPML 订阅列表。",
  "Import or export app preferences only — no feeds, folders, tags, or articles. Exports as rss-dashboard-settings-bundle.json":
    "仅导入或导出应用偏好，不包含订阅源、文件夹、标签或文章。导出文件为 rss-dashboard-settings-bundle.json",
  "Import or export feeds, folders, tags, articles, and article state — no app settings. Exports as rss-dashboard-feed-bundle.json":
    "导入或导出订阅源、文件夹、标签、文章及文章状态，不包含应用设置。导出文件为 rss-dashboard-feed-bundle.json",
  "Import or export plugin preferences. Exports as rss-dashboard-user-preferences.json":
    "导入或导出插件偏好。导出文件为 rss-dashboard-user-preferences.json",
  "Import or export shard data bundles for cross-device migration. Exports as rss-dashboard-portable-bundle.json":
    "导入或导出用于设备迁移的分片数据包。导出文件为 rss-dashboard-portable-bundle.json",
  'Import or export your full dashboard dataset as a single flat JSON file, including preferences, folders, feeds, and stored article retrievals. This is always the full legacy-format file, even when vault-shard storage is enabled — it will not match the small pointer file named data.json in your vault in that mode. Use "Shard data" below for a bundle that matches shard storage.':
    "将完整面板数据集作为单个 JSON 文件导入或导出，其中包含偏好、文件夹、订阅源和已保存的文章内容。无论是否启用保险库分片存储，此文件始终采用完整的旧版格式；启用分片存储时，它与保险库中的小型 data.json 索引文件不同。若需导出与分片存储匹配的数据包，请使用下方的“分片数据”。",
  "Import starred articles from a Google Reader-compatible starred.json export. Feeds you don't already subscribe to are created for you.":
    "从 Google Reader 兼容的 starred.json 文件导入已加星标文章。尚未订阅的订阅源会自动创建。",
  "Inline (inside dashboard)": "内嵌在面板中",
  "Keep articles saved to your vault when retention limits are applied":
    "应用保留期限时保留已保存到保险库的文章",
  "Keep starred articles when retention limits are applied":
    "应用保留期限时保留已加星标的文章",
  "Keep tagged articles when retention limits are applied":
    "应用保留期限时保留带标签的文章",
  "Keep unread articles when retention limits are applied":
    "应用保留期限时保留未读文章",
  "Leftover article state file": "遗留文章状态文件",
  "Keyword rules": "关键词规则",
  "Left sidebar": "左侧边栏",
  "Legacy JSON": "旧版 JSON",
  "Legacy JSON storage enabled.": "已启用旧版 JSON 存储。",
  "Line height": "行高",
  "List toolbar style (mobile)": "列表工具栏样式（移动端）",
  Load: "载入",
  "Load this template into the editor": "将此模板载入编辑器",
  "Main view": "主视图",
  "Main view (split)": "主视图（分屏）",
  "Max item limit": "文章数量上限",
  "Maximum storage for cached dashboard preview images, in MiB. Lowering this limit removes least-recently-used cached images immediately.":
    "面板预览图片缓存的最大容量（MiB）。调低此上限会立即删除最近最少使用的缓存图片。",
  Media: "媒体",
  "Metadata actions": "metadata 操作",
  "Metadata data.json location": "metadata data.json 位置",
  "Metadata location is already active.": "此 metadata 位置已经生效。",
  "Metadata storage": "metadata 存储",
  "Minimal (read/unread only)": "精简（仅显示已读/未读）",
  "Mixed (previous per-view values)": "混合（沿用各视图之前的设置）",
  "Mobile toolbar": "移动端工具栏",
  Mono: "等宽字体",
  "No ads, no tracking, no paywalls.": "没有广告、跟踪或付费墙。",
  "No cache size limit": "不限制缓存大小",
  "No storage changes to apply.": "没有需要应用的存储更改。",
  "No highlight words configured. Add words below to highlight them in articles.":
    "尚未设置高亮单词。请在下方添加要在文章中高亮的单词。",
  None: "无",
  Normal: "标准",
  OPML: "OPML",
  "Only highlight complete words (not partial matches)":
    "仅匹配完整单词，不匹配部分内容",
  "Only match this word/phrase with exact letter case":
    "仅匹配大小写完全一致的单词或短语",
  "Other plugins by the author": "作者的其他插件",
  "Paragraph spacing": "段落间距",
  Partial: "部分匹配",
  "Partial match": "部分匹配",
  "Playback progress": "播放进度",
  "Player theme": "播放器主题",
  "Podcast player": "播客播放器",
  "Protect saved articles": "保留已保存文章",
  "Protect starred articles": "保留已加星标文章",
  "Protect tagged articles": "保留带标签的文章",
  "Protect unread articles": "保留未读文章",
  "Protected from auto-deletion": "从自动删除中保护",
  Proxy: "代理",
  "Proxy URL": "代理 URL",
  Reader: "阅读器",
  "Reader view location": "阅读器打开位置",
  "Remember playback progress": "记住播放进度",
  "Reset icon order & visibility": "重置图标顺序和显示状态",
  "Remove all remembered podcast and video resume positions stored by the plugin":
    "删除插件记录的所有播客和视频续播位置",
  "Repair/rebuild storage": "修复/重建存储",
  Reset: "重置",
  "Reset folder names": "重置文件夹名称",
  "Reset reader format": "重置阅读器排版",
  "Reset tag names": "重置标签名称",
  "Reset the reader format defaults": "恢复阅读器排版默认值",
  "Results shown per page": "每页显示数量",
  "Restore all folder names to their out-of-the-box defaults.":
    "将所有文件夹名称恢复为初始默认值。",
  "Restore all plugin settings to their default values and clear plugin-managed data. Existing backup files and saved article markdown files are left untouched.":
    "将插件设置恢复为默认值并清除插件管理的数据。现有备份文件和已保存的文章 Markdown 文件不会受影响。",
  "Restore all tag names to their out-of-the-box defaults.":
    "将所有标签名称恢复为初始默认值。",
  "Restore the reader format defaults": "恢复阅读器排版默认值",
  "Row spacing": "行间距",
  "RSS Dashboard is a free, open-source community plugin for Obsidian that makes it easy to manage your RSS feeds, YouTube subscriptions, and podcasts in one place.":
    "RSS Dashboard 是一款免费的 Obsidian 开源社区插件，方便你在一个位置管理 RSS 订阅、YouTube 订阅和播客。",
  "RSS Dashboard was originally created by": "RSS Dashboard 最初由 ",
  ", with active development and support offered by":
    " 创建，自 2.2.0 版本起由 ",
  "since version 2.2.0, alongside many contributions from the community.":
    "持续开发和维护，并由社区贡献者共同完善。",
  "Report issue": "反馈问题",
  "Save as template": "另存为模板",
  "Save and restore podcast and video playback position across reader and plugin restarts":
    "在阅读器或插件重启后保留并恢复播客和视频的播放位置",
  "Save full content": "保存完整内容",
  "Save path": "保存路径",
  "Save to list": "保存到列表",
  "Saved article open location": "已保存文章的打开位置",
  "Saved templates": "已保存模板",
  "Saves a copy to data.json.backup in the plugin folder.":
    "在插件文件夹中保存一份 data.json.backup 副本。",
  "Saves a copy to feeds.opml.backup in the plugin folder.":
    "在插件文件夹中保存一份 feeds.opml.backup 副本。",
  "Saves a copy to the user preferences backup file in the plugin folder.":
    "在插件文件夹中保存一份用户偏好备份。",
  "Select a proxy...": "选择代理...",
  "Settings bundle": "设置数据包",
  "Shard data": "分片数据",
  "Shard storage v1": "分片存储 v1",
  "Shard storage v2": "分片存储 v2",
  "Show cover images": "显示封面图片",
  "Show feed fetch error badges": "显示订阅源获取错误标记",
  "Show a warning icon in the sidebar for feeds that failed to fetch":
    "订阅源获取失败时，在侧边栏显示警告图标",
  "Show filter status bar": "显示筛选状态栏",
  "Show per-article action buttons in card view on mobile":
    "在移动端卡片视图中显示文章操作按钮",
  "Show per-article action buttons in list view on mobile":
    "在移动端列表视图中显示文章操作按钮",
  "Show the dashboard status bar with retrieved and filtered article counts":
    "显示面板状态栏及获取、筛选后的文章数量",
  "Show summary": "显示摘要",
  "Show toolbar in card view (mobile)": "在卡片视图中显示工具栏（移动端）",
  "Show toolbar in list view (mobile)": "在列表视图中显示工具栏（移动端）",
  "Store card and feed preview images locally to improve browsing performance. Each image is limited to one megabyte and uses additional vault storage. RSS dashboard does not include this cache in feed or settings sync, but a sync tool that copies plugin files may copy it.":
    "将卡片和订阅流预览图片缓存在本地，以提升浏览性能。每张图片最多 1 MB，并会占用额外的保险库空间。RSS Dashboard 不会在订阅源或设置同步中包含此缓存，但同步插件文件的工具可能会复制缓存。",
  Sidebar: "侧边栏",
  "Sidebar padding": "侧边栏内边距",
  "Starred imports": "已加星标文章导入",
  "Startup filters": "启动时的筛选条件",
  "Startup refresh delay": "启动刷新延迟",
  Storage: "存储",
  "Storage actions": "存储操作",
  "Storage folder": "存储文件夹",
  "Storage mode": "存储模式",
  "Storage status": "存储状态",
  "Tag color": "标签颜色",
  "Tag name": "标签名称",
  Tags: "标签",
  "Template for saved articles. All frontmatter properties must start with a single space indent.":
    "已保存文章使用的模板。所有 frontmatter 属性前必须缩进一个空格。",
  "Third-party services": "第三方服务",
  "Toggle case sensitivity": "切换大小写敏感",
  "Toggle whole-word matching": "切换完整单词匹配",
  Update: "更新",
  "Update this template with current editor content":
    "使用当前编辑器内容更新此模板",
  "Use first-seen date for undated items": "无发布日期时使用首次发现日期",
  "Use this when shard storage seems out of sync, incomplete, or after manual folder moves. This will: 1. Re-check and normalize your storage folder path. 2. Force-rewrite all shard files from current feed data. 3. Force-save storage metadata. 4. Refresh storage status. Think of this as a safe 're-generate all shard files' action.'":
    "当分片存储不同步、内容不完整或手动移动文件夹后，可使用此功能。它会：1. 重新检查并规范存储文件夹路径；2. 根据当前订阅源数据强制重写所有分片文件；3. 强制保存存储 metadata；4. 刷新存储状态。此操作会重新生成全部分片文件。",
  "Use web viewer": "使用网页浏览器",
  "Use web viewer core plugin for articles when available":
    "网页浏览器核心插件可用时，用它打开文章",
  "Timeout in seconds for fetching full article content (prevents hanging)":
    "获取完整文章内容的超时时间（秒），用于防止请求一直等待",
  "User preferences file": "用户偏好文件",
  "View style": "视图样式",
  Whole: "完整单词",
  "Whole word": "完整单词",
  "Whole word only": "仅完整单词",
  "Word or phrase": "单词或短语",
  "YouTube profile images": "YouTube 频道头像",
  "YouTube RSS feeds do not provide channel profile images. Videos will always use the default video play icon.":
    "YouTube RSS 订阅源不提供频道头像，视频始终使用默认播放图标。",
  "YouTube terms of service": "YouTube 服务条款",
  "Feeds badge": "订阅源未读数标记",
  "Tag for video articles": "视频文章标签",
  "Tag used for auto-tagged YouTube content": "自动添加到 YouTube 内容的标签",
  "Default tag for Mastodon feeds": "Mastodon 订阅源的默认标签",
  "Default tag for podcast episodes": "播客节目的默认标签",
  "Default tag for RSS articles": "RSS 文章的默认标签",
  "Default tag for smallweb articles": "Smallweb 文章的默认标签",
  "Default tag for RSS articles with detected video content (YouTube feeds use the dedicated tag below)":
    "检测到视频内容的 RSS 文章使用此默认标签（YouTube 订阅源使用下方专属标签）",
  "Select default video tags": "选择默认视频标签",
  "Select default Mastodon tags": "选择默认 Mastodon 标签",
  "Select default YouTube tags": "选择默认 YouTube 标签",
  "Select default podcast tags": "选择默认播客标签",
  "Select default RSS tags": "选择默认 RSS 标签",
  "Select default smallweb tags": "选择默认 Smallweb 标签",
  "Tag names restored to defaults.": "标签名称已恢复默认值。",
  "Folders badge color": "文件夹标记颜色",
  "Feeds badge color": "订阅源标记颜色",
  "All feeds badge color": "全部订阅源标记颜色",
  "Hide toolbar entirely": "完全隐藏工具栏",
  "Default folder names": "恢复默认文件夹名称",
  "Vault folder for per-feed shard files. Adding a '.' prefix to the path will hide the folder. The '.' must be removed for Obsidian sync to work properly.":
    "保存每个订阅源分片文件的保险库文件夹。路径以“.”开头时该文件夹会被隐藏；如需使用 Obsidian Sync，请移除开头的“.”。",
  "Optional vault folder for metadata data.json. Leave empty to keep metadata in the plugin folder. Shard storage v2 keeps article state (user-state.json) in this folder too. After a location change, you can delete the previous data.json and, in v2, user-state.json, or keep them as a backup. Outside v2, an orphaned user-state.json is kept as a backup. Use a folder without a '.' prefix for Obsidian Sync.":
    "可选的 metadata data.json 保险库文件夹。留空则继续将 metadata 保存在插件文件夹中。分片存储 v2 也会在此文件夹保存文章状态（user-state.json）。更改位置后，可删除旧的 data.json，以及 v2 模式下的 user-state.json，也可以将它们留作备份。非 v2 模式下，遗留的 user-state.json 会作为备份保留。使用 Obsidian Sync 时，请选择名称不以“.”开头的文件夹。",
  "This will also limit the timeframe window for shown articles.":
    "此设置也会限制文章显示的时间范围。",
  "When an article has no publish date (common with some proxied feeds), use the date it was first seen instead of hiding it from sorting and auto-delete. Off by default. Changes are applied on the next feed refresh.":
    "文章没有发布日期时（某些代理订阅源较常见），使用首次发现日期参与排序和自动删除，而不是忽略该文章。默认关闭，更改会在下次刷新订阅源时生效。",
  "When an article is opened, it will be automatically marked as read":
    "打开文章时自动将其标记为已读",
  "When enabled, article fetches that are blocked by a firewall (e.g. On iOS) will be retried through the proxy URL below":
    "启用后，文章请求被防火墙拦截时（例如 iOS 上），将通过下方代理 URL 重试",
  "Get started with keyword rules": "开始设置关键词规则",
  "No keyword rules configured.": "尚未设置关键词规则。",
  "No rules configured yet.": "尚未设置规则。",
  "Support development": "支持开发",
  "Content can be saved directly to your vault.":
    "内容可以直接保存到你的保险库。",
  "Template reset to default": "模板已恢复默认值",
  "Build details copied": "构建信息已复制",
  "Import or export a OPML subscription list containing your configured feed addresses.":
    "导入或导出包含已配置订阅源地址的 OPML 订阅列表。",
  "Store preview images locally to improve browsing performance. Each image is limited to one megabyte and uses additional vault storage.":
    "将预览图片缓存在本地以提升浏览性能。每张图片最多 1 MB，并会占用额外的保险库空间。",
  "This item has no published date.": "此项目没有发布日期。",
  "Saved article files will use this template.":
    "已保存的文章文件将使用此模板。",
  No: "否",
  Yes: "是",
  All: "全部",
  Unread: "未读",
  Starred: "已加星标",
  Read: "已读",
  Enabled: "已启用",
  Disabled: "已停用",
  "Migration ready": "可以迁移",
  "Shard Storage v2 active": "分片存储 v2 已启用",
  "Shard Storage v1 active": "分片存储 v1 已启用",
  "Legacy JSON active": "旧版 JSON 已启用",
  "80%": "80%",
  "90%": "90%",
  "100%": "100%",
  "110%": "110%",
  "120%": "120%",
  "130%": "130%",
  "140%": "140%",
  "150%": "150%",
  "160%": "160%",
  "175%": "175%",
  "180%": "180%",
  "200%": "200%",
  "0.75x": "0.75 倍",
  "1x": "1 倍",
  "1.25x": "1.25 倍",
  "1.5x": "1.5 倍",
  "1.75x": "1.75 倍",
  "2x": "2 倍",
  "2.5x": "2.5 倍",
  "3x": "3 倍",
  "1 day": "1 天",
  "3 days": "3 天",
  "1 week": "1 周",
  "2 weeks": "2 周",
  "1 month": "1 个月",
  "2 months": "2 个月",
  "3 months": "3 个月",
  "6 months": "6 个月",
  "1 year": "1 年",
  "1 hour": "1 小时",
  "2 hours": "2 小时",
  "4 hours": "4 小时",
  "8 hours": "8 小时",
  "12 hours": "12 小时",
  "10 items": "10 篇",
  "25 items": "25 篇",
  "50 items": "50 篇",
  "100 items": "100 篇",
  "200 items": "200 篇",
  "500 items": "500 篇",
  "1000 items": "1000 篇",
  "5 minutes": "5 分钟",
  "10 minutes": "10 分钟",
  "15 minutes": "15 分钟",
  "30 minutes": "30 分钟",
  "24 hours": "24 小时",
  "Absolute (e.g. 'may 9, 2026, 11:39 am')":
    "具体日期（例如 2026 年 5 月 9 日 11:39）",
  "Add new proxy URL...": "添加新的代理 URL...",
  "Auto-cycle (try all proxies on failure)":
    "自动轮换（代理失败时尝试其他代理）",
  Bottom: "下方",
  "Bottom row": "底部排列",
  "Card view": "卡片视图",
  "Custom...": "自定义...",
  Default: "默认",
  "Feed view": "订阅流视图",
  Gradient: "渐变",
  "Left grid (2x2)": "左侧网格（2×2）",
  "List view": "列表视图",
  Loose: "宽松",
  Minimal: "简约",
  Off: "关闭",
  "Relative (e.g. '2 days ago')": "相对时间（例如 2 天前）",
  "Right sidebar": "右侧边栏",
  Serif: "衬线字体",
  "Solarized dark": "Solarized 深色",
  "Theme default": "跟随主题",
  Tight: "紧凑",
  "Tokyo night": "Tokyo Night",
  Top: "上方",
  Unlimited: "不限",
  "Reset to default": "恢复默认",
  "Available variables:": "可用变量：",
  "{{date}} (Long format)": "{{date}}（长日期格式）",
  "{{dateShort}} (YYYY-MM-DD)": "{{dateShort}}（YYYY-MM-DD）",
  "{{date:FORMAT}} (Moment.js format, e.g. {{date:YYYY/MM/DD}})":
    "{{date:FORMAT}}（Moment.js 格式，例如 {{date:YYYY/MM/DD}}）",
  "{{firstSeen}} (Date this article was first seen in the dashboard, independent of the 'Use first-seen date for undated items' display setting; falls back to the publish date if unavailable)":
    "{{firstSeen}}（文章首次出现在面板中的日期，不受“无发布日期时使用首次发现日期”设置影响；若无此日期则使用发布日期）",
  "{{saveDate}} (Local save date YYYY-MM-DD)":
    "{{saveDate}}（本地保存日期 YYYY-MM-DD）",
  "{{saveTime12}} (Local save time 12-hour format, e.g. 02:45 PM)":
    "{{saveTime12}}（本地保存时间，12 小时制，例如 02:45 PM）",
  "{{saveTime24}} (Local save time 24-hour military format, e.g. 14:45)":
    "{{saveTime24}}（本地保存时间，24 小时制，例如 14:45）",
  "[{{tags}}] (array of tags e.g. [tag1, tag2, ...])":
    "[{{tags}}]（标签数组，例如 [tag1, tag2, ...]）",
  "No saved templates yet. Save the current template using the button above.":
    "还没有已保存的模板。点击上方按钮保存当前模板。",
};
